feat: update name and use for_each function in code
clouddrove/terraform-aws-sftp pull request #40
Opened 2024-01-25 10:28 UTC by theprashantyadav

## what
* Fix naming convention and use format function
* Use for_each function in aws_transfer_ssh_key resource
* Update s3 and subnet version 
## why
* Need to update naming convention
* Need to update for_each function

2024-01-26 10:06 UTC, themaniskshah approved these changes, later dismissed

2024-02-07 10:58 UTC, evgenyidf requested changes
Running from scratch returns error:
`
aws_transfer_user.transfer_server_user["s3docs"]: Creation complete after 1s [id=s-ae723d54cf4247849/s3docs]

can you please "additional_tags' variable and merge with 

`
  tags = merge(module.labels.tags, var.additional_tags)
`
╷
│ Error: importing ssh public key: ResourceNotFoundException: Unknown user
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "35e823db-e9c3-4f50-a587-ed4ec236410d"
│   },
│   Message_: "Unknown user",
│   Resource: "s3docs",
│   ResourceType: "User"
`

2024-02-07 10:58 UTC, evgenyidf commented on main.tf
> +  name                = format("%s-sftp-users", module.labels.id)
I think uou will get errors if more then one user will be defined for sftp

2024-02-20 10:27 UTC, theprashantyadav commented on main.tf
> +  name                = format("%s-sftp-users", module.labels.id)
@evgenyidf Hello 
Yes, I have done it using for_each function. Now such error will not occur

2024-02-20 17:42 UTC, themaniskshah approved these changes

2024-03-13 08:01 UTC, nileshgadgi approved these changes

2026-08-09 03:01 UTC, closed without merging